## NumPy Random Numbers

In [36]:
## A random number is a number that cannot be predicted

#If you toss a coin, you cannot predict whether it will be Head or Tail.
#Similarly, random numbers are unpredictable

### Pseudo Random vs True Random

In [37]:
## Pseudo Random

# Computers generate random numbers using an algorithm (program)
# Since the computer follows instructions, these numbers are not truly random

# They are called Pseudo Random Numbers

from numpy import random

print(random.randint(100))
print(random.randint(100))
print(random.randint(100))
print(random.randint(100))

# Output (changes every run)

# Although the output looks random, it is generated by an algorithm

68
51
15
65


In [38]:
## True Random

# True random numbers come from outside sources such as:

#Mouse movement
#Keyboard typing
#Weather sensors
#Network activity

# These are mostly used in:

#Encryption
#Security
#Password generation

#For normal programming and data science, Pseudo Random Numbers are sufficient


In [39]:
# Import Random Module

from numpy import random

#Now -> use all random functions

### random.randint()

In [40]:
# random.randint()

# Used to generate random integers

#Syntax ->   random.randint(max)

from numpy import random

x = random.randint(121)
y = random.randint(121)
z = random.randint(121)
print(x)
print(y)
print(z)

# Output : The number is between 0 and 120


108
4
90


In [41]:
## Generate Multiple Random Integers

x = random.randint(100, size = 5)
print(x)

# 100 → numbers from 0–99
# size=5 → generate 5 numbers

[13 81  6 40 40]


In [42]:
## Generate 2D Random Integer Array

x = random.randint(100, size = (3,5))
# (3,5) -> 3 rows and 5 columns

print(x)


[[68 28 49 11 73]
 [44 41 95 79 51]
 [19 52  2 72 38]]


### random.rand()

In [43]:
## random.rand()

# Used to generate random decimal (float) numbers

# Range: 0 ≤ number < 1

x = random.rand()
print(x)


0.05639229736252582


In [44]:
## Multiple Float Numbers

x = random.rand(4)
print(x)


[0.77161329 0.48819423 0.29806676 0.50493013]


In [45]:
## 2D Float Array

x = random.rand(3,4)
# (3,4) -> 3 rows, 4 columns

print(x)

[[0.43437698 0.28844797 0.60427391 0.68763232]
 [0.72354267 0.34613371 0.32379844 0.44546912]
 [0.45329878 0.99267314 0.11718209 0.2398343 ]]


### random.choice()

In [46]:
## random.choice()

# Used to randomly select values from an existing array

x = random.choice([3,4,2,1])
y = random.choice([3,4,2,1])
print(x)
print(y)


1
4


In [47]:
## Generate Multiple Random Choices

x = random.choice([12,4,2,4,623,1,0], size = 3)
print(x)


[623  12   4]


In [48]:
## Generate 2D Random Array

x = random.choice([12,3,2,6,0,9,234,876,4523,21,3], size = (3,4))
print(x)


[[ 234    9    0   12]
 [   3  234    6    2]
 [  21 4523    3  234]]


## Random Data Distribution

In [49]:
## Random Data Distribution

# A data distribution tells: 
# Which values are possible
# How likely each value is to appear

#Example

#Suppose we have four values:

# 3
# 5
# 7
# 9

# want

# 3 → 10%
# 5 → 30%
# 7 → 60%
# 9 → 0%

# Instead of giving every value the same chance, we assign different probabilities


### Probability (p)

In [50]:
## Probability (p)
num = [3,5,7,9]
p = [0.1,0.3,0.6,0]

#Means

# Value	Probability
# 3	    0.1 (10%)
# 5	    0.3 (30%)
# 7	    0.6 (60%)
# 9	    0.0 (0%)

# 0.1 + 0.3 + 0.6 + 0 = 1
# The probabilities must always add up to 1

In [51]:
## Example

from numpy import random

x = random.choice(
    [3,5,7,9],
    p = [0.1,0.3,0.6,0],
    size = 20
)

print(x)

# 7 appears most often
# 3 appears rarely
# 9 never appears

[3 7 7 5 7 5 5 5 5 5 7 7 5 7 7 5 7 7 3 7]


In [52]:
## 2D Probability Distribution

from numpy import random

x = random.choice(
    [3,5,7,9],
    p = [0.1,0.3,0.6,0],
    size = (3,5)
)

print(x)

[[3 7 5 7 5]
 [5 7 5 7 7]
 [7 3 7 7 5]]


## Random Permutations

In [ ]:
## Random Permutations

# A permutation means arranging the same elements in a different order

## Example

# Original:

# [1 2 3]

# Possible permutations:

# [3 2 1]
# [2 1 3]
# [1 3 2]

# The values remain the same; only their order changes

### shuffle()

In [ ]:
## shuffle()

# Shuffle changes the original array

from numpy import random
import numpy as np

arr = np.array([1,2,4,231,78,45,0])

random.shuffle(arr)

print(arr)

# The original array itself becomes:
# [ 45   0   4  78   2   1 231]

#So shuffle() modifies the existing array in-place

# The original array has changed

[ 45   0   4  78   2   1 231]


### permutation()

In [ ]:
## permutation()

# permutation() also rearranges the elements, but does not change the original array

import numpy as np
from numpy import random

arr = np.array([1,2,367,89,32,0,211])

new_arr = random.permutation(arr)
print(new_arr)

print(arr)

# The original array remains unchanged


[ 89 211 367   0   2  32   1]
[  1   2 367  89  32   0 211]


In [ ]:
arr = np.array([1,2,3,4,5,0])

random.shuffle(arr)

print(arr)

# Original array has changed


[3 1 0 4 2 5]


In [ ]:
arr = np.array([1,2,3,4,5,0])

new_arr = random.permutation(arr)

print(new_arr)
print(arr)

# Original array is unchanged

[5 2 0 4 1 3]
[1 2 3 4 5 0]


In [ ]:
# Function	            Purpose
# random.randint()	Generate random integers
# random.rand()	    Generate random float numbers (0–1)
# random.choice()	    Pick random values from an array
# p=	                Assign probability to each value
# shuffle()	        Rearrange elements and modify the original array
# permutation()	    Return a shuffled copy without changing the original array