# NUMPY UFUNC

## NumPy Summations

In [2]:
## NumPy Summations

## Difference between add() and sum()

## np.add() -> Adds two arrays element by element

import numpy as np
arr1 = np.array([12,34,5,6])
arr2 = np.array([6,54,23,1])

print(np.add(arr1,arr2))


[18 88 28  7]


In [4]:
## np.sum() -> Adds all elements together

import numpy as np
arr1 = np.array([12,34,5,6])
arr2 = np.array([6,54,23,1])

print(np.sum([arr1,arr2]))

141


### Sum Over Axis

In [ ]:
import numpy as np
arr1 = np.array([12,34,5,6])
arr2 = np.array([6,54,23,1])

print(np.sum([arr1,arr2], axis = 1))

# Row 1 Calculate -> 12+34+5+6 = 57
# Ror 2 Calculate -> 6+54+23+1 = 84

[57 84]


### Cumulative Sum (cumsum())

In [ ]:
## Cumulative Sum (cumsum())

# It keeps adding previous values

arr = np.array([1,2,3,4])

print(np.cumsum(arr))

# 1
# 1+2 = 3
# 1+2+3 = 6
# 1+2+3+4 = 10


[ 1  3  6 10]


## NumPy Products

In [ ]:
## NumPy Products

# Product means multiplication

# Prod()

arr = np.array([1,2,3,4])

print(np.prod(arr))

# 1×2×3×4 = 24

24


### Product of Two Arrays

In [ ]:
## Product of Two Arrays

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(np.prod([arr1, arr2]))

# 1*2*3*4*5*6*7*8

40320


### Product over Axis

In [9]:
## Product over Axis

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(np.prod([arr1,arr2], axis = 1))

# Row 1 ->  1*2*3*4 = 24
# Row 2 -> 5*6*7*8 = 1680

[  24 1680]


### Cumulative Product (cumprod())

In [ ]:
## Cumulative Product (cumprod())

arr = np.array([5,6,7,8])

print(np.cumprod(arr))

# 5
# 5*6 = 30
# 5*6*7 = 210
# 5*6*7*8 = 1680

[   5   30  210 1680]


## NumPy Differences (diff())

In [ ]:
## NumPy Differences (diff())

# Finds difference between consecutive elements

arr = np.array([10,15,25,5])

print(np.diff(arr))

# 15 - 10 = 5
# 25 - 15 = 10
# 5 - 25 = -20

[  5  10 -20]


### Using n=2

In [16]:
## Using n=2

arr = np.array([10,15,25,5])
print(np.diff(arr, n = 2))

# Step 1 -> [5,10,-20]

###Step 2  
# 10-5 = 5 
# -20-10 = -30

[  5 -30]


## LCM (Lowest Common Multiple)

In [17]:
## LCM (Lowest Common Multiple)

# Smallest number divisible by both numbers

print(np.lcm(4,6))

12


### LCM of Array

In [19]:
## LCM of Array

arr = np.array([3,6,15])

print(np.lcm.reduce(arr))


30


## GCD (Greatest Common Divisor)

In [20]:
## GCD (Greatest Common Divisor)

# Largest number that divides both numbers

print(np.gcd(6,9))


3


### GCD of Array

In [21]:
## GCD of Array

arr = np.array([20,8,32,36,16])

print(np.gcd.reduce(arr))

4


## Trigonometric Functions

In [ ]:
## Trigonometric Functions

# These functions use radians, not degrees

### sin()

In [22]:
## sin()

print(np.sin(np.pi/2))

1.0


### cos()

In [23]:
## cos()

print(np.cos(0))

1.0


### tan()

In [25]:
## tan()

print(np.tan(np.pi/4))

0.9999999999999999


### Convert Degrees to Radians

In [26]:
## Convert Degrees to Radians

arr = np.array([90,180,270,360])

print(np.deg2rad(arr))

[1.57079633 3.14159265 4.71238898 6.28318531]


### Convert Radians to Degrees

In [27]:
## Convert Radians to Degrees

arr = np.array([np.pi/2, np.pi])

print(np.rad2deg(arr))


[ 90. 180.]


### Inverse Trigonometric Functions

In [ ]:
## Inverse Trigonometric Functions

# These return angles

print(np.arcsin(1))


1.5707963267948966


### Hypotenuse (hypot())

In [29]:
## Hypotenuse (hypot())

# Uses Pythagoras theorem

print(np.hypot(3,4))


5.0


## Hyperbolic Functions

In [ ]:
## Hyperbolic Functions

# Similar to trigonometric functions but used in advanced mathematics, engineering, and machine learning

## Main Functions:

np.sinh()

np.cosh()

np.tanh()


In [30]:
# Example

print(np.sinh(np.pi/2))

2.3012989023072947


In [ ]:
## Inverse Functions
np.arcsinh()

np.arccosh()

np.arctanh()


## NumPy Set Operations

In [ ]:
## NumPy Set Operations
# A set contains only unique values

### unique()

In [ ]:
## unique()

arr = np.array([1,1,2,3,4,2,4])

print(np.unique(arr))

#Duplicates are removed

[1 2 3 4]


### union1d()

In [ ]:
## union1d()

# Combines unique elements from two arrays

arr1 = np.array([1,2,3,4,6,5,1])
arr2 = np.array([6,8,1,9,10,3])

print(np.union1d(arr1,arr2))

[ 1  2  3  4  5  6  8  9 10]


### intersect1d()

In [ ]:
## intersect1d()

# Common elements

arr1 = np.array([1,2,3,4,6,5,10])
arr2 = np.array([6,8,1,9,10,3])

print(np.intersect1d(arr1,arr2))

[ 1  3  6 10]


### setdiff1d()

In [ ]:
## setdiff1d()

# Elements present in first array only

arr1 = np.array([1,2,3,4,6,5,10])
arr2 = np.array([6,8,1,9,10,3])

print(np.setdiff1d(arr1,arr2))


[2 4 5]


### setxor1d()

In [ ]:
## setxor1d()

# Elements that exist in only one of the arrays (not in both) -> remove common elements

arr1 = np.array([1,2,3,4,6,5,10])
arr2 = np.array([6,8,1,9,10,3])

print(np.setxor1d(arr1,arr2))

[2 4 5 8 9]


In [ ]:

# Function	                                       Purpose
# np.add()	                                  Add two arrays element-wise
# np.sum()	                                  Sum all elements
# np.cumsum()	                              Running total
# np.prod()	                                  Multiply all elements
#np.cumprod()	                              Running multiplication
#np.diff()	                                  Difference between consecutive elements
# np.lcm()	                                  Lowest Common Multiple
# np.gcd()	                                  Greatest Common Divisor
# np.sin(), np.cos(), np.tan()	              Trigonometric functions
# np.deg2rad()	                              Degrees → Radians
# np.rad2deg()	                              Radians → Degrees
# np.arcsin(), np.arccos(), np.arctan()	      Inverse trigonometric functions
# np.hypot()	                              Calculate hypotenuse
# np.sinh(), np.cosh(), np.tanh()	          Hyperbolic functions
# np.unique()	                              Remove duplicates
# np.union1d()	                              Union of two arrays
# np.intersect1d()	                          Common elements
# np.setdiff1d()	                          Elements only in first array
# np.setxor1d()	                              Elements not common to both arrays