# NumPy ufuncs (Universal Functions)

In [74]:
## What are ufuncs?

## ufunc stands for Universal Function.

## These are built-in NumPy functions that work directly on NumPy arrays (ndarray)
## Instead of processing one element at a time using loops, ufuncs process the entire array at once



In [75]:
# Why use ufuncs?

## ufuncs are much faster than Python loops because they use vectorization

#Advantages:

# - Faster execution
# - Less code
# - Works directly with arrays
# - Supports broadcasting
# - Supports methods like reduce(), accumulate()

#### Vectorization

In [76]:
## What is Vectorization?

# Vectorization means performing an operation on the entire array at once instead of using loops

## Without Vectorization

x = [1,2,3,4,5]
y = [2,3,789,0,1]

z = []

for i,j in zip(x,y):
    z.append(i+j)

print(z)

## Python adds elements one by one using a loop

[3, 5, 792, 4, 6]


In [77]:
## With Vectorization (ufunc)

import numpy as np

x = [1,2,3,4,5]
y = [2,3,789,0,1]

z = np.add(x,y)

print(z)

# No loop is required

# NumPy automatically adds every corresponding element


[  3   5 792   4   6]


## Create Your Own ufunc

In [78]:
# Normally NumPy provides many ufuncs

# You can also create your own

In [79]:
## Step 1: Create a normal function

def myadd(x,y):
    return x+y

## Step 2: Convert it into ufunc

# Syntax -> np.frompyfunc(function, inputs, outputs)
## function	-> Function name
## inputs ->  Number of input arguments
## outputs -> Number of output values

import numpy as np

myadd = np.frompyfunc(myadd,2,1)


In [80]:
## Example

import numpy as np

def myadd(x,y):
    return x+y

myadd = np.frompyfunc(myadd,2,1)

print(myadd([1,2,3],[12,3,4]))


[13 5 7]


#### Check if a Function is a ufunc

In [81]:
## Check if a Function is a ufunc

import numpy as np

print(type(np.add))

# <class 'numpy.ufunc'> -> It means add() is a ufunc

<class 'numpy.ufunc'>


In [82]:
## Example

print(type(np.concatenate))

# concatenate() is not a ufunc

<class 'numpy._ArrayFunctionDispatcher'>


### Using if Statement

In [83]:
## Using if Statement

import numpy as np

if type(np.add) == np.ufunc:
    print("add is ufunc")
else:
    print("add is not ufunc")



add is ufunc


## Simple Arithmetic ufuncs

In [84]:
## Simple Arithmetic ufuncs

## These functions perform arithmetic on two arrays element by element

### 1. add()

In [85]:
#  Adds corresponding elements

import numpy as np

arr1 = np.array([1,2,3,45,5])
arr2 = np.array([1,2,32,78,9])

print(np.add(arr1,arr2))


[  2   4  35 123  14]


### 2. subtract()

In [86]:
## Subtracts second array from first array

import numpy as np

arr1 = np.array([1,2,3,45,5])
arr2 = np.array([1,2,32,78,9])

print(np.subtract(arr1,arr2))


[  0   0 -29 -33  -4]


### 3. multiply()

In [87]:
## Multiplies corresponding elements

import numpy as np

arr1 = np.array([1,2,3,45,5])
arr2 = np.array([1,2,32,78,9])

print(np.multiply(arr1,arr2))


[   1    4   96 3510   45]


### 4. divide()

In [88]:
## Divides first array by second array

import numpy as np

arr1 = np.array([1,2,3,45,5])
arr2 = np.array([1,2,32,78,9])

print(np.divide(arr1,arr2))


[1.         1.         0.09375    0.57692308 0.55555556]


### 5. power()

In [89]:
## Raises first array values to the power of second array values

import numpy as np

arr1 = np.array([1,2,3,5,5])
arr2 = np.array([1,2,2,8,9])

print(np.power(arr1,arr2))


[      1       4       9  390625 1953125]


### 6. mod() / remainder()

In [90]:
## Returns the remainder after division

import numpy as np

arr1 = np.array([1,2,32,78,9])
arr2 = np.array([1,2,3,45,5])

print(np.mod(arr1,arr2))

print(np.remainder(arr1,arr2))

## np.mod() and np.remainder() produce the same result


[ 0  0  2 33  4]
[ 0  0  2 33  4]


### 7. divmod()

In [91]:
## Returns both quotient and remainder

import numpy as np

arr1 = np.array([10,20,30])
arr2 = np.array([3,7,9])

print(np.divmod(arr1,arr2))

#In Output:
# First array -> Quotient
# Second Array -> Remainder

(array([3, 2, 3]), array([1, 6, 3]))


### 8. absolute()

In [92]:
## Converts negative numbers into positive numbers

arr = np.array([1,-2,33,-56,-9,-32])

print(np.absolute(arr))

# Absolute value simply removes the negative sign

[ 1  2 33 56  9 32]


## NumPy Rounding Functions

In [93]:
## Rounding Functions

# NumPy provides several ways to round decimal numbers

### trunc()

In [94]:
## trunc()

# Removes the decimal part

arr = np.array([23.34, 45.91,-23.0])

print(np.trunc(arr))

# It simply cuts off the decimal part


[ 23.  45. -23.]


### fix()

In [95]:
## fix()

# Works exactly like trunc()

arr = np.array([23.34, -45.91,23.0])

print(np.fix(arr))

[ 23. -45.  23.]


### around()

In [96]:
# around()

## Rounds to a specified number of decimal places

# (number, round decimal place number)
print(np.around(3.1116,2))
print(np.around(3.1116,3))
print(np.around(3.1386,2))

3.11
3.112
3.14


### floor()

In [97]:
## floor()

# Rounds down to the nearest integer

print(np.floor([3.1, -3.6, 4.9, -5.1]))

# Floor always moves downward

[ 3. -4.  4. -6.]


### ceil()

In [98]:
## ceil()

# Rounds up to the nearest integer

print(np.ceil([3.1, -3.6, 4.9, -5.1]))

# Ceil always moves upward

[ 4. -3.  5. -5.]


## ufunc NumPy Logs

In [99]:
# NumPy Logs

# A logarithm answers the question:

# "To what power should the base be raised to get the given number?

## Example
# 2³ = 8
# So
# log₂(8)=3


### log2()

In [100]:
## log2()

# Calculates logarithm with base 2

import numpy as np 
arr = np.arange(1,10)
print(np.log2(arr))

# log₂(1)=0

# log₂(2)=1

# log₂(4)=2

# log₂(8)=3


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


### log10()

In [101]:
## log10()

# Calculates logarithm with base 10

arr = np.arange(1,10)

print(np.log10(arr))


# log₁₀(1)=0

# log₁₀(10)=1

# log₁₀(100)=2

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


### log()

In [102]:
## log()

# Calculates the natural logarithm (base e)

arr=np.arange(1,10)
print(np.log(arr))

## e = 2.71828

# This function is widely used in mathematics, statistics, and machine learning

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


### Log with Any Base

In [103]:
# NumPy has no direct function for arbitrary bases

# You can create one using frompyfunc()

from math import log
import numpy as np

nplog = np.frompyfunc(log,2,1)
print(nplog(100,10))

# 10² =100
# Therefore
# log₁₀(100)=2


2.0


In [104]:
### Quick Revision

# Function	                   Purpose
# np.add()	                Add two arrays
# np.subtract()	            Subtract arrays
# np.multiply()	            Multiply arrays
# np.divide()	                Divide arrays
# np.power()	                Exponentiation (x^y)
# np.mod() / np.remainder()	Find remainder
# np.divmod()	                Return quotient and remainder
# np.absolute()	            Convert negatives to positives
# np.trunc()	                Remove decimal part
# np.fix()	                Same as trunc()
# np.around()	                Round to specified decimal places
# np.floor()	                Round down
# np.ceil()	                Round up
# np.log2()	                Base-2 logarithm
# np.log10()	                Base-10 logarithm
# np.log()	                Natural logarithm (base e)
# np.frompyfunc()	            Create a custom ufunc