# Python Modules

## 1. NumPy

### NumPy Getting Started

In [160]:
#NumPy Introduction

#What is NumPy?

#NumPy (Numerical Python) is a Python library used for working with arrays and performing fast mathematical operations

#It is mainly used in:

#Data Science
#Machine Learning
#Artificial Intelligence
#Data Analysis

In [161]:
#Why do we use NumPy?

#Normally, Python uses lists to store data

numbers = [1,2,3,4,5,5]
print(numbers)

#But lists become slow when working with a large amount of data


[1, 2, 3, 4, 5, 5]


In [162]:
#NumPy Install Command
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [163]:
# NumPy provides arrays, which are much faster

import numpy as np

arr = np.array([1,2,3,45,6,7,54,32,1])
print(arr)

[ 1  2  3 45  6  7 54 32  1]


In [164]:
# Why is NumPy faster than Python Lists?

#Python List
# 1
# 2
# 3
# 4
# 5

# Data is stored in different memory locations

# NumPy Array
# 1 2 3 4 5

# Data is stored continuously in memory

# Because of continuous memory storage:

#Faster calculations
#Less memory usage
#Better CPU performance

In [165]:
##Import NumPy

# Instead of writing
import numpy

# we usually write
import numpy as np

# Why "np"?

#np is an alias (short name)

#Instead of writing    ->  numpy.array()

#we simply write   ->      np.array()

#Much shorter and easier


In [166]:
##Example

import numpy as np

arr = np.array([1,3,2,4,6,4,2])
print(arr)


[1 3 2 4 6 4 2]


In [167]:
# Check NumPy Version

import numpy as np
print(np.__version__)



2.1.0


### NumPy Creating Arrays

In [168]:
#Use

#   np.array()

#Example

import numpy as np
arr = np.array([12,23,1,"ali"])
print(arr)

#Also Use Tuple
arr = np.array((12,23,1,"ali"))
print(arr)


['12' '23' '1' 'ali']
['12' '23' '1' 'ali']


In [169]:
## Check Array Type

import numpy as np 
arr = np.array([1,2,3,"alisha"])
print(type(arr))

#Output : <class 'numpy.ndarray'>
#the object is a NumPy array



<class 'numpy.ndarray'>


In [170]:
## Dimensions in NumPy

# Dimensions tell us how many levels an array has

# 0-D Array(Scalar)
#Contains only one value

import numpy as np 
arr = np.array(12) #Dimension = 0
print(arr)

12


In [171]:
## 1-D Array

#Contains multiple values in one line

arr = np.array([1,23,4,56,9]) #Dimension = 1
print(arr)


[ 1 23  4 56  9]


In [172]:
## 2-D Array

#Rows and Columns

arr = np.array([[1,2,3,4,5],
                [12,34,5,6,7]])   #Dimension = 2

print(arr)

[[ 1  2  3  4  5]
 [12 34  5  6  7]]


In [173]:
## 3-D Array

# A collection of 2-D arrays

arr = np.array([
    [[1,2],[23,45]],
    [[32,12],[45,32]]
])   #Dimension = 3
#Matrix Form
print(arr)


[[[ 1  2]
  [23 45]]

 [[32 12]
  [45 32]]]


In [174]:
## Check Number of Dimensions

# use -> .ndim
a = np.array(12)
b = np.array([12.3,4,56,2,1])
c = np.array([[1,3,56],
                [12,3,4]])
d = np.array([
    [[1,2],[23,45]],
    [[32,12],[45,32]]
]) 

#Number of Dimensions
print(a.ndim)  
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [175]:
## Create Higher Dimensions

#Use -> ndmin = number of dimensions

import numpy as np

arr = np.array([12,23,1,2,3], ndmin = 5)
print(arr)
print(arr.ndim)

# Even though there are only three numbers, NumPy creates 5 dimensions

[[[[[12 23  1  2  3]]]]]
5


### NumPy Array Indexing

In [176]:
## Array Indexing
# Index means the position of an element

# Indexes start from 0

arr = np.array([10,20,30,40])
#Index        0   1  2  3

##Access Elements
print(arr[0])
print(arr[2])
#print(arr[5]) #IndexError: index 5 is out of bounds for axis 0 with size 4

## Add Elements
print(arr[2]+arr[3])


10
30
70


In [177]:
# 2-D Array Indexing

#Number of elements in all rows -> equal

arr = np.array([[101,2,31],   #Row 0
                [4,25,6]])  #Row 1  

### Access  -> print(array[row, index])

print(arr[0,2])

print(arr[1,0])

print(arr[1,1])


31
4
25


In [178]:
## 3-D Indexing

arr = np.array([
    [[1,2,3],
    [4,5,6]],
    
    [[7,8,9],
    [10,11,12]]
])

### Access -> print(array[block/matrix index, row index, element index])

print(arr[0,1,2])   # element 6

print(arr[1,0,1])  # element 8


6
8


In [179]:
## Negative Indexing

# Negative Indexing starts from the end -> from right to left

arr = np.array([1, 23, 14, 15, 32, 1, 56])
#index         -7, -6, -5, -4, -3,-2, -1

print(arr[-1])
print(arr[-2])
print(arr[-6])


56
1
23


### NumPy Array Slicing

In [180]:
## Array Slicing

# Slicing means taking a part of an array

# [start : end]

# Start included
# End excluded 

arr = np.array([12,3,4,5,6])

print(arr[1:4])

[3 4 5]


In [181]:
## From Index 4 to end 

arr = np.array([1,2,3,4,56,7,734,2,12,34,5,6])

print(arr[4:])

[ 56   7 734   2  12  34   5   6]


In [182]:
## Beginning to index 5

arr = np.array([1,2,3,4,56,7,734,2,12,34,5,6])

print(arr[:5]) #end excluded


[ 1  2  3  4 56]


In [183]:
## Step in Slicing

# Syntax ->   [start:end:step]

arr = np.array([1,2,3,4,56,7,734,2,12,34,5,6])

print(arr[1:8:3])  #It skips every third element
print(arr[1:10:2])  #It skips every second element


[ 2 56  2]
[ 2  4  7  2 34]


In [184]:
## Whole array with step

arr = np.array([1,2,3,4,56,7,734,2,12,34,5,6])

print(arr[::2])


[  1   3  56 734  12   5]


In [185]:
## 2-D Array Slicing

arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

#Syntax -> print(array[row index, start : end])

print(arr[1,1:4])


[7 8 9]


In [186]:
## Multiple rows, Column

arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

#arr[rows, columns]
print(arr[0:2,2])    #First number = Row
#                     Second number = Column

#  0:2
#Start from Row 0
#End before Row 2

# 2 
# Column 2 from each selected row


[3 8]


In [187]:
# Multiple Rows , Multiple Columns

# Rows 0–1 and columns 1–3

arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

print(arr[0:2,1:4])


# 0:2 -> Rows 0,1

# 1:4 -> Columns 1,2,3 from rows



[[2 3 4]
 [7 8 9]]


Q1. What is NumPy?
Answer: NumPy is a Python library used for arrays and fast mathematical operations

Q2. What does NumPy stand for?
Answer: Numerical Python

Q3. Why is NumPy faster than Python lists?
Answer: Because NumPy stores data in continuous memory locations, making operations faster and more efficient

Q4. What is an ndarray?
Answer: It is the array object provided by NumPy

Q5. Which function creates a NumPy array?
Answer: np.array()

Q6. Which attribute tells the number of dimensions?
Answer: .ndim

Q7. What is slicing?
Answer: Slicing is used to extract a portion of an array

Q8. What is indexing?
Answer: Indexing is used to access individual elements of an array

Q9. What is the difference between indexing and slicing?

Indexing returns a single element
Slicing returns multiple elements (a sub-array)

### NumPy Data Types

In [188]:
## NumPy Data Types

# Just like Python, NumPy stores different kinds of data

name = "Ali"      # String
age = 20          # Integer
marks = 85.5      # Float
passed = True     # Boolean

# NumPy Data Types

# NumPy uses short letters for data types

# Code	  Meaning
# i	      Integer
# f	      Float
# b	      Boolean
# S	      String
# U	    Unicode String
# c	    Complex Number
# O	       Object



In [189]:
## Check Data Types

import numpy as np

arr = np.array([1,23,4,4])

print(arr.dtype)

#int64 -> Array stores integers

int64


In [190]:
arr = np.array (["alisha","sajjad"])
print(arr.dtype)

# <U6 -> Unicode String

<U6


In [191]:
## Create Array with Specific Data Type

# Suppose your values are integers but you want them as strings

arr = np.array([1,2,3,4,5], dtype = "S")

print(arr)
print(arr.dtype)

# Everything becomes string

[b'1' b'2' b'3' b'4' b'5']
|S1


In [192]:
## Another Example

arr = np.array([12,3,4,23], dtype = "f")
print(arr)
print(arr.dtype)

# Integers became floats


[12.  3.  4. 23.]
float32


In [193]:
## Convert Existing Data Type (astype())

arr = np.array([1.2,34.3,113.6,2.01])   # Current type = float
print(arr)
print(arr.dtype)

# Convert into integer

new_arr = arr.astype(int)   #Decimal part is removed
print(new_arr)
print(new_arr.dtype)


[  1.2   34.3  113.6    2.01]
float64
[  1  34 113   2]
int64


In [194]:
## Convert Integer to Boolean

arr = np.array([1,0,3,2,0])
print(arr)
print(arr.dtype)

# Convert into boolean
new_arr = arr.astype(bool)
print(new_arr)
print(new_arr.dtype)

#0  -> False
#Any non-zero number -> True

[1 0 3 2 0]
int64
[ True False  True  True False]
bool


### NumPy Array Copy vs View

In [195]:
# Copy

# A copy creates a completely new array

#    Original
#    [1 2 3]
#       ↓

#      Copy
#     [1 2 3]

#Both are Separate


In [196]:
#Example

arr = np.array([1,2,3,4,1])
copy1 = arr.copy()

arr[0] = 101   #array 0 index change 

print(arr)  # Original changed
print(copy1) # Copy did NOT change

[101   2   3   4   1]
[1 2 3 4 1]


In [197]:
## View
# View shares the same memory

# Original
#     ↑
#     ↓
# View

# Both point to same data

In [198]:
## Example

arr = np.array([1,2,34,3,9])
view1 = arr.view()

arr[1] = 222 #Original Changed

print(arr)  
print(view1) 

# Both changed


[  1 222  34   3   9]
[  1 222  34   3   9]


In [199]:
## Change View

arr = np.array([12,34,12,31,21,11,112,1211])
view2 = arr.view()

view2[-1] = 0

print(arr)
print(view2)
# Changing view also changes original

[ 12  34  12  31  21  11 112   0]
[ 12  34  12  31  21  11 112   0]


In [200]:
## base Attribute

# To know whether array owns its own data

arr = np.array([122,0,1,4,21])

#Copy

x = arr.copy()
print(x)
print(x.base) #None ->  Means copy owns its data

# copy() creates a completely new array
#It has its own memory

# arr -----> Memory A
# copy_arr -----> Memory B

# Both are separate


#View

y = arr.view()
print(y)
print(y.base) #Output array -> Means view uses original array's memory

# view() does NOT create new memory
# It only points to the original array


# It is mainly used to check whether an array is a Copy or a View






[122   0   1   4  21]
None
[122   0   1   4  21]
[122   0   1   4  21]


### NumPy Array Shape

In [201]:
#Shape tells:
# How many rows and columns (or dimensions) an array has

In [202]:
# Example

# number of columns in all rows -> equal

arr = np.array([[1,2,3,1],
                [1,2,1,2]])

print(arr.shape)

#(2, 4) -> means 2 rows and 4 columns


(2, 4)


In [203]:
arr = np.array([1,2,3,1])
print(arr.shape)

# (4,) -> one dimension -> 4 elements


(4,)


### NumPy Array Reshaping

In [204]:
## Reshape

# Reshape changes the shape of an array without changing its data


In [205]:
## Example

arr = np.array([1,23,33,42,15,61])

new_arr = arr.reshape(2,3) #(row,columns)

print(new_arr)


[[ 1 23 33]
 [42 15 61]]


In [206]:
## 1D - > 3D

arr = np.array([1,2,3,4,5,6,7,8,9])

new_arr = arr.reshape(3,3)

print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [207]:
arr = np.array([1,2,3,4,5,6,7,8])

new_arr = arr.reshape(2,2,2) # 2 matrix

print(new_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [208]:
##Rule -> Total elements must stay the same

#Correct Way
# 12 elements

# reshape(3,4)
# 3 × 4 = 12

#Wrong Way

#reshape(5,3)  -> Error
#5 × 3 = 15  


In [209]:
### Unknown Dimension (-1)

arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,-1)

print(new_arr)

# NumPy automatically calculates the missing dimension

[[1 2 3]
 [4 5 6]]


In [210]:
### Flatten

# Convert multidimensional array into 1D

arr = np.array([[1,2],
                [3,4]])

new_arr = arr.reshape(-1)

print(new_arr)


[1 2 3 4]


### NumPy Array Iterating

In [211]:
## Iterating Arrays

# Iterating means visiting every element one by one

In [212]:
### 1-Dimension

arr = np.array([1,2,4,421,12])

for x in arr:
    print(x)



1
2
4
421
12


In [213]:
### 2-Dimensions

arr = np.array([[1,2],
                [32,12]])

for row in arr:
    print(row)

# Each iteration gives one row


[1 2]
[32 12]


In [214]:
### To print every value

for row in arr:
    for value in row:
        print(value)

1
2
32
12


In [215]:
### 3-Dimensions

# Need nested loops according to dimensions

arr = np.array([[[1,2],[12,33]],
                [[1221,231],[43,454]]
                ])

for row in arr:
    for column in row:
        for value in column:
            print(value)


1
2
12
33
1221
231
43
454


In [216]:
# Rows Print

for row in arr:
    print(row)


[[ 1  2]
 [12 33]]
[[1221  231]
 [  43  454]]


In [217]:
# Columns Print

for row in arr:
    for column in row:
        print(column)

[1 2]
[12 33]
[1221  231]
[ 43 454]


In [218]:
### nditer()

# Instead of many loops, NumPy provides nditer()

arr = np.array([[12,3,32],
                [12,3,4]])

for x in np.nditer(arr):
    print(x)

#Works for arrays of any dimension


12
3
32
12
3
4


In [219]:
## Example

arr = np.array([[[1,2],[12,33]],
                [[1221,231],[43,454]]
                ])

for x in np.nditer(arr):
    print(x)



1
2
12
33
1221
231
43
454


In [220]:
### ndenumerate()

# Returns both index and value

arr = np.array([1,2,3,4])

for index,value in np.ndenumerate(arr):
    print(index,value)



(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [221]:
arr = np.array([[1,2],
                [3,4]])

for index,value in np.ndenumerate(arr):
    print(index,value)


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [222]:
# Topic	             Purpose
# dtype	        Check data type of array
# astype()	    Convert one data type to another
# copy()	    Creates an independent copy
# view()	    Shares memory with original array
# shape	        Returns rows and columns (dimensions)
# reshape()	    Changes the shape of an array
# reshape(-1)	Flattens an array into 1D
# nditer()	    Iterates through all values easily
# ndenumerate()	Returns both index and value while iterating


### NumPy Joining Array

In [223]:
### What is Joining?

# Joining means combining two or more arrays into one array

In [224]:
# Example
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([12,5,1,9])

arr = np.concatenate((arr1,arr2))
print(arr)


[ 1  2  3  4 12  5  1  9]


#### concatenate()

In [225]:
## concatenate()

#  Syntax

#  np.concatenate((array1, array2), axis=0)

#  axis=0 is the default.

In [226]:
### Joining 2-D Arrays

arr1 = np.array([[1,2],
                [3,4]])

arr2 = np.array([[5,6],
                [7,8]])

arr = np.concatenate((arr1,arr2), axis = 1)
#axis = 1 means join columns

print(arr)


[[1 2 5 6]
 [3 4 7 8]]


In [227]:
### axis=0

arr = np.concatenate((arr1, arr2), axis=0)
#axis = 0 means Rows are added

print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### stack()

In [228]:
### stack()

# Stacking is almost the same as joining

#Difference:

#concatenate() joins on an existing axis
#stack() creates a new axis

In [229]:
## Example

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1,arr2))
print(arr)

#A new dimension is created

[[1 2 3]
 [4 5 6]]


In [230]:
## stack(axis = 1)

arr = np.stack((arr1,arr2), axis = 1)
print(arr)

# same column -> join 

[[1 4]
 [2 5]
 [3 6]]


#### hstack()

In [231]:
### hstack()

# Horizontal Stack

# Joins arrays side-by-side

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.hstack((arr1,arr2))
print(arr)


[1 2 3 4 5 6]


In [232]:
# For 2D arrays it joins columns

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[4,5],[34,5]])

arr = np.hstack((arr1,arr2))
print(arr)


[[ 1  2  4  5]
 [ 3  4 34  5]]


#### vstack()

In [233]:
### vstack()
# Vertical Stack

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.vstack((arr1,arr2))
print(arr)

#Arrays are placed one below another

[[1 2 3]
 [4 5 6]]


In [234]:
#Example
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[4,5],[34,5]])

arr = np.vstack((arr1,arr2))
print(arr)

[[ 1  2]
 [ 3  4]
 [ 4  5]
 [34  5]]


#### dstack()

In [235]:
### dstack()

# Stacks along the third dimension (depth)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,34])

arr = np.dstack((arr1,arr2))
print(arr)

print(arr.ndim)

# It creates a 3-D array

[[[ 1  4]
  [ 2  5]
  [ 3 34]]]
3


In [236]:
#Function	     Meaning
# concatenate()	 Join existing axis
# stack()	     Create new axis
# hstack()	     Horizontal
# vstack()	     Vertical
# dstack()	     Depth (3D)

### NumPy Splitting Array

In [237]:
# What is Splitting?

# Splitting is the opposite of joining

# Joining

# A + B
#   ↓
# One Array

# ------------------

# Splitting

#  One Array
#     ↓
#  A  B  C

In [238]:
### array_split()

arr = np.array([1,23,4,5])

new_arr = np.array_split(arr,3)
print(new_arr)

[array([ 1, 23]), array([4]), array([5])]


In [239]:
### split into 4 parts

arr = np.array([12,44,22,56,78,12,789,0,23,56,13,4,1])

new_arr = np.array_split(arr,4)
print(new_arr)

# Notice that array_split() automatically adjusts the sizes

[array([12, 44, 22, 56]), array([ 78,  12, 789]), array([ 0, 23, 56]), array([13,  4,  1])]


In [240]:
### Access Split Arrays

# new_arr -> [array([12, 44, 22, 56]), array([ 78,  12, 789]), array([ 0, 23, 56]), array([13,  4,  1])]

print(new_arr[0])

print(new_arr[-1])

[12 44 22 56]
[13  4  1]


In [241]:
### Split 2D Array

arr = np.array([[1,2],
                [3,4],
                [5,6],
                [7,8]
                ])

new_arr = np.array_split(arr,2)
print(new_arr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [242]:
### Split Columns 

arr = np.array([[1,2,3],
                [4,5,6]])

new_arr = np.array_split(arr,3,axis = 1)

print(new_arr)

# Each column becomes a separate array

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


### NumPy Searching Arrays

In [243]:
# NumPy Searching Arrays

# Searching means finding where a value exists

In [244]:
### where()

arr = np.array([1,2,7,3,4,5,6,7,101])

x = np.where(arr == 7)
print(x)

# (array([2, 7]),) -> means Value 7 exist in index 2 or 7

y = np.where(arr == 101)
print(y)

#  (array([8]),) -> means value 101 exist in index 8

z = np.where(arr == 1011)
print(z)

#  (array([], dtype=int64),) -> means value not exist

(array([2, 7]),)
(array([8]),)
(array([], dtype=int64),)


In [245]:
### Find Even Numbers

arr = np.array([1,2,34,53,44,76,909,100])

x = np.where(arr%2==0)
print(x)


(array([1, 2, 4, 5, 7]),)


In [246]:
### Find Odd Numbers

arr = np.array([1,2,34,53,44,76,909,100])

#y = np.where(arr%2==1) same as y = np.where(arr%2!=0)
y = np.where(arr%2!=0)
print(y)


(array([0, 3, 6]),)


In [247]:
### searchsorted()

#Used only on sorted arrays

#It tells where a value should be inserted

In [248]:
# Example

arr = np.array([6,7,8,9])

x = np.searchsorted(arr,7)
print(x)

#Output -> 1 -> Because 7 is already at index 1

1


In [249]:
arr = np.array([6,7,8])

x = np.searchsorted(arr,9)
print(x)

# 9 should be inserted at index 3

3


In [250]:
arr = np.array([1,3,5,7])

print(np.searchsorted(arr,4))

#4 should be inserted between 3 and 5 -> at index 2


2


In [251]:
### Multiple Values

arr = np.array([6,7,8,9,23])
print(np.searchsorted(arr,[1,10,15,56]))

#[0 4 4 5]

# 1 -> at index 0
# 10 -> at index 4
# 15 -> at index 4
# 56 -> at index 5

[0 4 4 5]


### NumPy Sorting Arrays

In [252]:
# NumPy Sorting Arrays

# Sorting means arranging values in order

In [253]:
### Numbers

arr = np.array([1,2,342,12,2,13,40,1,0])

print(np.sort(arr))


[  0   1   1   2   2  12  13  40 342]


In [254]:
### Strings
# Alphabetical order

arr = np.array(["sajjad", "alisha", "zarmeen", "ali"])
print(np.sort(arr))


['ali' 'alisha' 'sajjad' 'zarmeen']


In [255]:
### Strings -> Case Sensitive

#A-Z UpperCase ->  First 
#a-z lowerCase ->  after uppercase 

arr = np.array(["sajjad", "alisha", "Zarmeen", "ali"])
print(np.sort(arr))

['Zarmeen' 'ali' 'alisha' 'sajjad']


In [256]:
### Boolean

arr = np.array([True,False,False,True])
print(np.sort(arr))

#order: False First -> then True


[False False  True  True]


In [257]:
### 2D Sorting

arr = np.array([[2,3,4,4],
                [2,1,0,5]])

print(np.sort(arr))

# Each row is sorted separately

[[2 3 4 4]
 [0 1 2 5]]


### NumPy Filter Array

In [258]:
#NumPy Filtering Arrays

#Filtering means selecting only the elements that satisfy a condition

In [259]:
## Boolean Filter

arr = np.array([41,23,67,0])

x = [True,False,False,True]

print(arr[x])  #Only positions with True are selected


[41  0]


In [260]:
## Filter Values Greater Than 42

arr = np.array([41,23,67,100])

filter_arr = arr > 42

print(filter_arr)

print(arr[filter_arr]) ## Only Trues Values Returned

# 41 > 42 -> False
# 23 > 42 -> False
# 67 > 42 -> True
# 100 > 42 -> True



[False False  True  True]
[ 67 100]


In [261]:
## Filter Even Numbers

arr = np.array([42,23,67,100])

filter_arr = arr%2==0

print(filter_arr)

print(arr[filter_arr]) 

[ True False False  True]
[ 42 100]


In [262]:
#Function	       Purpose
#concatenate()    Join arrays on an existing axis
#stack()	      Join arrays by creating a new axis
#hstack()	      Horizontal stacking
#vstack()	      Vertical stacking
#dstack()	      Depth (3D) stacking
#array_split()	  Split one array into multiple arrays
#where()	      Find indices where a condition is true
#searchsorted()	  Find insertion index in a sorted array
#sort()	          Return a sorted copy of the array
#arr[condition]	  Filter elements based on a condition

